### ISSUE TITLE
Trigger master builds

### ISSUE THREAD

**Issue by KevinGrandon** [mvines/ci-gate#40]
I ported over all of our webhooks to use ci-gate, but it seems that master is no longer building. It'd be nice to also trigger master from this so we don't have to have two webhooks.

Wondering if you're open to doing this by default, or if we should have an environment variable to turn this on.

**Comment by mvines** [comment]
Hmm, it looks ok from here.  What's the error you're seeing?

I've got Travis running on PRs and pushes, http:://travis-ci.org/mvines/ci-gate, and a Heroku app that autodeploys at https://dashboard.heroku.com/apps/ci-gate (happy to make you an app collaborator if you'd like).  It's currently running your commit:
![image](https://user-images.githubusercontent.com/1281082/44549436-f09f0b80-a6d5-11e8-9ab3-36dc055b98ef.png)

**Comment by KevinGrandon** [comment]
Oh sorry, I mean that ci-gate should trigger buildkite builds for commits that land in the master branch. I think that the heroku ci-gate connection is probably fine.

**Comment by mvines** [comment]
Ah, right.    Yes.    Startup was failing with a:
```
Aug 23 13:08:42 solana-ci-gate app/web.1:  /app/index.js:1354 
Aug 23 13:08:42 solana-ci-gate app/web.1:      throw new Error(v + ' environment variable not defined'); 
Aug 23 13:08:42 solana-ci-gate app/web.1:      ^ 
Aug 23 13:08:42 solana-ci-gate app/web.1:  Error: BUILDKITE_EXPOSE_ALL_JOB_LOGS environment variable not defined 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Object.<anonymous> (/app/index.js:78:11) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Module._compile (internal/modules/cjs/loader.js:654:30) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at loader (/app/node_modules/babel-register/lib/node.js:144:5) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Module.load (internal/modules/cjs/loader.js:566:32) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at tryModuleLoad (internal/modules/cjs/loader.js:506:12) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Function.Module._load (internal/modules/cjs/loader.js:498:3) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Function.Module.runMain (internal/modules/cjs/loader.js:695:10) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Object.<anonymous> (/app/node_modules/babel-cli/lib/_babel-node.js:154:22) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Module._compile (internal/modules/cjs/loader.js:654:30) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Module.load (internal/modules/cjs/loader.js:566:32) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at tryModuleLoad (internal/modules/cjs/loader.js:506:12) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Function.Module._load (internal/modules/cjs/loader.js:498:3) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at Function.Module.runMain (internal/modules/cjs/loader.js:695:10) 
Aug 23 13:08:42 solana-ci-gate app/web.1:      at startup (internal/bootstrap/node.js:201:19) 
```

Fixed that via 4b99d59b663e88fdb2849c12053a87bb4b29ade6

**Comment by KevinGrandon** [comment]
> Ah, right. Yes. Startup was failing with a:

Ah, sorry about that and thanks for a fix!
